# Generated by Django 2.2.12 on 2022-06-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomCode', models.CharField(default='', max_length=8, unique=True)),
                ('host', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
