# Generated by Django 2.2.12 on 2022-06-24 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_list_delete_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='Completed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
