# Generated by Django 3.1.1 on 2022-06-24 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20220624_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['-Completed', '-date_updated', '-date_created']},
        ),
    ]
