# Generated by Django 3.1.1 on 2022-06-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20220624_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['-Completed', '-date_updated', '-date_created']},
        ),
    ]
